name: Build Docker Images and Push

on:
  push:
    branches: [ main ]

jobs:
  push_to_registry:
    strategy:
      matrix:
        os: [ubuntu]
        tag: [18.04, 20.04, 22.04]
    runs-on: ubuntu-latest
    steps:
    -
      name: Checkout
      uses: actions/checkout@v2
    -
      name: Create Dockerfile
      run: ./create-one-dockerfile.sh ${{ matrix.os }}:${{ matrix.tag }}
    -
      name: Set up QEMU
      uses: docker/setup-qemu-action@v1
    -
      name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    -
      name: Login to DockerHub
      uses: docker/login-action@v1 
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - 
      name: Build and push
      id: docker_build
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ${{ matrix.os }}${{ matrix.tag }}/Dockerfile
        tags: electronioncollider/spack-builder:${{ matrix.os }}${{ matrix.tag }}
        push: true
    -
      name: Image digest
      run: echo ${{ steps.docker_build.outputs.digest }}
