name: Build Docker Images

on:
  schedule:
    - cron: '43 2 * * *' # run at 2 AM UTC
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  push_to_registry:
    strategy:
      matrix:
        os: [centos7,centos8,ubuntu18.04,ubuntu19.10,ubuntu20.04,ubuntu20.10]
    runs-on: ubuntu-latest
    steps:
    -
      name: Checkout
      uses: actions/checkout@v2
    -
      name: Set up QEMU
      uses: docker/setup-qemu-action@v1
    -
      name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    -
      name: Login to DockerHub
      uses: docker/login-action@v1 
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - 
      name: Build and push
      id: docker_build
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ${{ matrix.os }}/Dockerfile
        tags: electronioncollider/spack-builder:${{ matrix.os }}-test
        push: true
    -
      name: Image digest
      run: echo ${{ steps.docker_build.outputs.digest }}
