name: Build Docker Images

on:
  push:
    branches-ignore: [ main ]
  pull_request:
    branches-ignore: [ main ]

jobs:
  build_only:
    strategy:
      matrix:
        os: [ubuntu18.04, ubuntu20.04, ubuntu22.04]
    runs-on: ubuntu-latest
    steps:
    -
      name: Checkout
      uses: actions/checkout@v2
    -
      name: Create Dockerfile
      run: ./create-one-dockerfile.sh ${{ matrix.os }}
    -
      name: Set up QEMU
      uses: docker/setup-qemu-action@v1
    -
      name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    - 
      name: Build and push
      id: docker_build
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ${{ matrix.os }}/Dockerfile
        tags: electronioncollider/spack-builder:${{ matrix.os }}
        push: false
    -
      name: Image digest
      run: echo ${{ steps.docker_build.outputs.digest }}
